# config/crawler_config.toml

# 공통 설정
[general]
log_level = "info"  # 로그 레벨: debug, info, error 등

# 데이터베이스 설정
[database]
user = "crawler_user"
password = "crawler_password"
host = "127.0.0.1"    # MySQL 호스트
port = "3306"         # MySQL 포트
name = "dipping"      # 데이터베이스 이름

# 서비스별 설정
[[services]]
name = "Babechat"
endpoint = "https://api.babechatapi.com/ko/api/characters/babies"
interval = 10  # 호출 주기: 초 단위

[[services]]
name = "Wrtn"
endpoint = "https://api.wrtnapi.com/data"
interval = 3600  # 호출 주기: 초 단위 (1시간)

[[services]]
name = "Lofan"
endpoint = "https://api.lofanapi.com/api/characters"
interval = 3600  # 호출 주기: 초 단위 (1시간)